GET http://localhost:3500/bugs

###
GET http://localhost:3500/bugs/64cc281cc2380133281ff1cc

###
POST http://localhost:3500/bugs
content-type: application/json

{
    "issue": "testing status",
    "details": "testing status",
    "priority": "High"  
}

###
PATCH http://localhost:3500/bugs/64cc281cc2380133281ff1cc
content-type: application/json

{
    "notes": "update check 12345",
    "status": "Completed",
    "priority": "meh"
}

###
DELETE http://localhost:3500/bugs/64cad44ee23d8e2d6c91ab12


###
POST http://localhost:3500/auth/register
Content-Type: application/json

{
    "name": "maira",
    "email": "maira3@gmail.com",
    "password":"M@ira1992"
}

###
POST http://localhost:3500/auth/refresh
Content-Type: application/json
{
    "jwt": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZGZmZTJiOTYwNGMwOTQyNzU5OGM1OSIsImlhdCI6MTY5MjQwMTE5NSwiZXhwIjoxNjkzMDA1OTk1fQ.rvhK_o--RSwRc5smUKaICIYXyyj5Y_FmVgx9k6srmv0"
}



