GET http://localhost:3500/bugs

###
GET http://localhost:3500/bugs/64b5b2461f038848968c3058

###
POST http://localhost:3500/bugs
content-type: application/json

{
    "issue": "issue6",
    "details": "details6"
}

###
PATCH http://localhost:3500/bugs/64b5b2461f038848968c3058
content-type: application/json

{
    "details": "update here"
}

###
DELETE http://localhost:3500/bugs/64b5b2461f038848968c3058